Implement variant setting for some

diff --git a/chive b/chive
--- a/chive
+++ b/chive
@@ -30,9 +30,8 @@ Options:
    -c, --check VARIANT ...    check variants
 
    --help                     show version information of $PROG_NAME
-   --version                  show this help and exit
-"
-    exit 1
+   --version                  show this help and exit"
+    exit
 }
 
 
@@ -240,90 +239,124 @@ v_add() {
 }
 
 
+# Switch to a particular variant for targets
+v_switch() {
+    local alt_body alt_vpath begin body end match offset t_path target v_path
+    local arr=("${!1}")
+    local variant="$2"
+
+    for target in "${arr[@]}"; do
+        v_path="$CONFIG_DIR/$target/$variant"
+
+        # reset
+        match=0
+
+        # Skip targets that don't have the current variant or if their
+        # variants are empty
+        [[ ! -f "$v_path" || ! -s "$v_path" ]] && continue
+
+        # Get target file name
+        t_path="$(head -n 1 "$CONFIG_DIR/$target/.config")"
+
+        # If target file doesn't exist, die
+        [[ ! -f "$t_path" ]] && die "file \"$t_path\" does not exist\n" "$t_path"
+
+        # Get variant body
+        body="$(v_body "$v_path")"
+
+        # See if the variant's body is being used
+        if pcregrep -M -q "^${body}$" "$t_path"; then
+            continue
+        else
+            # The variant is currently not being used, so check if another
+            # variant is in use. If so, we can replace it. If not, then
+            # there's nothing we can do so we'll consider this variant
+            # invalid.
+            for alt_vpath in "$CONFIG_DIR"/"$target"/*; do
+                # Skip empty/duplicate variants
+                [[ ! -s "$alt_vpath" || "$alt_vpath" == "$v_path" ]] && continue;
+
+                # Get variant body
+                alt_body="$(v_body "$alt_vpath")"
+
+                # Check if variant has a match
+                #
+                # Note that we use t_path instead of t_path2. That's
+                # because while this variant has a match, its target
+                # path may be invalid or different (though I don't
+                # really see that happening). So just to be safe, we
+                # use t_path.
+                if pcregrep -M -q "^${alt_body}$" "$t_path"; then
+                    match=1
+                    break
+                fi
+            done
+
+            if [[ "$match" -eq 1 ]]; then
+                # Another variant that has a match, so we can switch
+                begin="$(pcregrep -M -n "^${alt_body}$" "$t_path" | head -n 1 | cut -d: -f1)"
+                offset="$(wc -l <<< "$alt_body")"
+                end=$((begin + offset - 1))
+
+                sed -i "${begin},${end}d" "$t_path"
+                awk -i inplace -v a="$begin" -v b="$body" "NR==a{print b}1" "$t_path"
+            else
+                # There was no match, so die
+                die "invalid variant: $target-$variant"
+            fi
+        fi
+    done
+}
+
+
 # Set variants for specific targets
 v_setsome() {
-    local v_path
+    local copy=() current_targets=() done_targets=()
+    local flag=0
 
-    for variant in "${variants[@]}"; do
-        for target in "${targets[@]}"; do
-            v_path="$CONFIG_DIR/$target/$variant"
+    for name in "$@"; do
+        if in_array targets[@] "$name"; then
+            current_targets+=("$name")
+            flag=0
+            continue
+        fi
 
-            # Skip targets that don't have the template or have empty ones
-            [[ ! -f "$v_path" || ! -s "$v_path" ]] && continue
-        done
+        [[ "$flag" -eq 1 ]] && die "attempted multi-variant switch"
+
+        if (( "${#current_targets[@]}" > 0 )); then
+            v_switch current_targets[@] "$name"
+
+            for t in "${current_targets[@]}"; do
+                if ! in_array done_targets[@] "$t"; then
+                    done_targets+=("$t")
+                fi
+            done
+
+            current_targets=()
+        elif (( "${#current_targets[@]}" == 0 )); then
+            copy=("${ALL_TARGETS[@]}")
+
+            for del in "${done_targets[@]}"; do
+                copy=("${copy[@]/"$del"}")
+            done
+
+            v_switch copy[@] "$name"
+        fi
+
+        flag=1
     done
 }
 
 
 # Set a variant for all targets
 v_setall() {
-    local alt_body alt_vpath begin body end match offset t_path target v_path variant
+    local variant
 
     # Prevent multiple variants from being specified for all targets
-    (( "${#variants[@]}" > 1 )) && die "multiple templates cannot be applied to multiple targets"
+    (( "${#variants[@]}" > 1 )) && die "attempted multi-variant switch"
 
     for variant in "${variants[@]}"; do
-        for target in "${ALL_TARGETS[@]}"; do
-            v_path="$CONFIG_DIR/$target/$variant"
-
-            # reset
-            match=0
-
-            # Skip targets that don't have the current variant or if their
-            # variants are empty
-            [[ ! -f "$v_path" || ! -s "$v_path" ]] && continue
-
-            # Get target file name
-            t_path="$(head -n 1 "$CONFIG_DIR/$target/.config")"
-
-            # If target file doesn't exist, die
-            [[ ! -f "$t_path" ]] && die "file \"$t_path\" does not exist\n" "$t_path"
-
-            # Get variant body
-            body="$(v_body "$v_path")"
-
-            # See if the variant's body is being used
-            if pcregrep -M -q "^${body}$" "$t_path"; then
-                continue
-            else
-                # The variant is currently not being used, so check if another
-                # variant is in use. If so, we can replace it. If not, then
-                # there's nothing we can do so we'll consider this variant
-                # invalid.
-                for alt_vpath in "$CONFIG_DIR"/"$target"/*; do
-                    # Skip empty/duplicate variants
-                    [[ ! -s "$alt_vpath" || "$alt_vpath" == "$v_path" ]] && continue;
-
-                    # Get variant body
-                    alt_body="$(v_body "$alt_vpath")"
-
-                    # Check if variant has a match
-                    #
-                    # Note that we use t_path instead of t_path2. That's
-                    # because while this variant has a match, its target
-                    # path may be invalid or different (though I don't
-                    # really see that happening). So just to be safe, we
-                    # use t_path.
-                    if pcregrep -M -q "^${alt_body}$" "$t_path"; then
-                        match=1
-                        break
-                    fi
-                done
-
-                if [[ "$match" -eq 1 ]]; then
-                    # Another variant that has a match, so we can switch
-                    begin="$(pcregrep -M -n "^${alt_body}$" "$t_path" | head -n 1 | cut -d: -f1)"
-                    offset="$(wc -l <<< "$alt_body")"
-                    end=$((begin + offset - 1))
-
-                    sed -i "${begin},${end}d" "$t_path"
-                    awk -i inplace -v a="$begin" -v b="$body" "NR==a{print b}1" "$t_path"
-                else
-                    # There was no match, so die
-                    die "invalid variant: $target-$variant"
-                fi
-            fi
-        done
+        v_switch ALL_TARGETS[@] "$variant"
     done
 }
 
